options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Create the Docker image for the frontend application
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/serverless-data-processing-prj/serverless-frontend/qdp:latest', '.']

  # Step 2: Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/serverless-data-processing-prj/serverless-frontend/qdp:latest']

  # Step 3: Deploy the image to Cloud Run as a managed service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/serverless-data-processing-prj/serverless-frontend/qdp:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'


  # Step 4: Make the Cloud Run service publicly accessible
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - 'frontend-service'
      - '--region'
      - 'us-central1'
      - '--member=allUsers'
      - '--role=roles/run.invoker'

images:
  - 'us-central1-docker.pkg.dev/serverless-data-processing-prj/serverless-frontend/qdp:latest'
